pa수정

diff --git a/.github/workflows/PA.yml b/.github/workflows/PA.yml
--- a/.github/workflows/PA.yml
+++ b/.github/workflows/PA.yml
@@ -73,10 +73,11 @@ jobs:
         run: |
           git fetch origin main
           git switch -c main origin/main
-          if ! git merge --ff origin/release -m "Merge release into main with merge commit(ff)"; then
-            echo "FF merge failed, falling back to no-FF merge."
-            git merge --no-ff origin/release -m "Merge release into main with merge commit(no ff)"
-          fi
+          git merge --ff origin/release -m "Merge release into main with merge commit(ff)
+          # if ! git merge --ff origin/release -m "Merge release into main with merge commit(ff)"; then
+            # echo "FF merge failed, falling back to no-FF merge."
+            # git merge --no-ff origin/release -m "Merge release into main with merge commit(no ff)"
+          # fi
           git push origin main
       - name: rollback if failure
         if: ${{ failure() }}
